In [4]:
import torch
import numpy as np
from adaline import ADALINE

In [2]:
X = torch.tensor([
    [2, 3],
    [1, 1],
    [2, 1],
    [-1, -1],
    [-2, -3],
    [-1, -2]
])

y = torch.tensor([1, 1, 1, -1, -1, -1])
model = ADALINE(lerrate=0.01)
model.fit(X,y)

In [3]:
x_pre =torch.tensor([[2,3],[2,1],[-1, -2]])
model.predict(x_pre)

tensor([[ 1],
        [ 1],
        [-1]], device='mps:0')

In [20]:
X = torch.randn(10,3)
y = torch.randint(0,2,(10,))

In [21]:
y

tensor([0, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [22]:
X

tensor([[-1.6141,  1.1169, -2.2774],
        [ 0.3459,  0.4530, -0.0797],
        [-0.7672, -1.6183,  0.2508],
        [-0.0767,  0.8628, -0.5376],
        [ 0.2985,  1.0875, -0.4366],
        [ 0.2142, -0.2821, -0.5899],
        [ 0.7447,  0.3285, -0.7132],
        [ 1.0758, -0.7097, -1.4567],
        [ 0.1681,  0.3479,  0.4778],
        [-1.2193, -2.0820, -1.1839]])

In [23]:
torch.seed()
ind = torch.randperm(X.shape[0])
X,y = X[ind],y[ind]
ind

tensor([5, 9, 2, 1, 4, 3, 0, 8, 7, 6])

In [24]:
X

tensor([[ 0.2142, -0.2821, -0.5899],
        [-1.2193, -2.0820, -1.1839],
        [-0.7672, -1.6183,  0.2508],
        [ 0.3459,  0.4530, -0.0797],
        [ 0.2985,  1.0875, -0.4366],
        [-0.0767,  0.8628, -0.5376],
        [-1.6141,  1.1169, -2.2774],
        [ 0.1681,  0.3479,  0.4778],
        [ 1.0758, -0.7097, -1.4567],
        [ 0.7447,  0.3285, -0.7132]])

In [26]:
from torch.utils.data import TensorDataset, DataLoader
dataset = TensorDataset(X, y)

# Create DataLoader
loader = DataLoader(dataset, batch_size=2, shuffle=True)
for epoch in range(5):
    for batch_X, batch_y in loader:
        print(batch_X.shape)  
        print(batch_y.shape) 


torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
torch.Size([2, 3])
torch.Size([2])
