In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from io import StringIO

In [3]:
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
1.0,11.0,12.0,
'''
df =pd.read_csv(StringIO(csv_data))

In [3]:
df.head()

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  1.0  11.0  12.0  NaN

In [4]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [6]:
#convert pd datafarame to numpy array, which is more convinent for scikitlearn 
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [ 1., 11., 12., nan]])

In [7]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
df_drop =df.dropna(axis=1)

In [20]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  1.0  11.0  12.0  NaN

In [21]:
df_drop

A     B
0  1.0   2.0
1  5.0   6.0
2  1.0  11.0

In [5]:
#mean impute
df.fillna(df.mean())

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.5  8.0
2  1.0  11.0  12.0  6.0

In [8]:
df['C'].fillna(df['C'].mean(),inplace=True)

/var/folders/7b/pb4y2ycs0s5fhd1y7ddbk2500000gn/T/ipykernel_1578/2998786113.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['C'].fillna(df['C'].mean(),inplace=True)


In [9]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.5  8.0
2  1.0  11.0  12.0  NaN

In [27]:
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'IT', 'HR', 'IT', 'HR'],
    'Salary': [50000, 60000, 45000, np.nan, np.nan, 55000, 65000, np.nan],
    'Absent':['N','N','Y',np.nan,np.nan,'N','N','Y']
}
df_1 = pd.DataFrame(data)

In [28]:
df_1.head()

Department   Salary Absent
0         IT  50000.0      N
1         IT  60000.0      N
2         HR  45000.0      Y
3         HR      NaN    NaN
4         IT      NaN    NaN

In [29]:
df_1['Salary'].fillna(df_1.groupby('Department')['Salary'].transform('mean').round(2),inplace=True)

/var/folders/7b/pb4y2ycs0s5fhd1y7ddbk2500000gn/T/ipykernel_1578/2754502792.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_1['Salary'].fillna(df_1.groupby('Department')['Salary'].transform('mean').round(2),inplace=True)


In [30]:
df_1

Department    Salary Absent
0         IT  50000.00      N
1         IT  60000.00      N
2         HR  45000.00      Y
3         HR  50000.00    NaN
4         IT  58333.33    NaN
5         HR  55000.00      N
6         IT  65000.00      N
7         HR  50000.00      Y

In [38]:
df_1['Absent']=df_1['Absent'].fillna(df_1['Absent'].mode()[0])

In [39]:
df_1

Department    Salary Absent
0         IT  50000.00      N
1         IT  60000.00      N
2         HR  45000.00      Y
3         HR  50000.00      N
4         IT  58333.33      N
5         HR  55000.00      N
6         IT  65000.00      N
7         HR  50000.00      Y

In [41]:
df_1['Absent'].mode()

0    N
Name: Absent, dtype: object

In [4]:
df_cat =pd.DataFrame([['green', 'M', 10.1, 'class2'],
['red', 'L', 13.5, 'class1'],
['blue', 'XL', 15.3, 'class2']])
df_cat.columns=['color', 'size', 'price', 'classlabel']

In [5]:
df_cat

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [6]:
encode ={'M':1,'L':2,'XL':3}
df_cat['size']=df_cat['size'].map(encode)

In [7]:
df_cat

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [8]:
decode = {v:k for k,v in encode.items()}
df_cat['size']=df_cat['size'].map(decode)
df_cat

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

{1: 'M', 2: 'L', 3: 'XL'}

In [9]:
{v:k for k,v in enumerate(np.unique(df_cat['classlabel']))}

{'class1': 0, 'class2': 1}

In [15]:
from sklearn.preprocessing import LabelEncoder
label_en =LabelEncoder()
y=label_en.fit_transform(df_cat.classlabel.values)
y


array([1, 0, 1])

In [16]:
label_en.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

In [17]:
df_cat

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [35]:
from sklearn.preprocessing import OneHotEncoder
color_en = OneHotEncoder(sparse_output=False)
x=color_en.fit_transform(df_cat[['color']].values)



In [39]:
pd.get_dummies(df_cat)

price  color_blue  color_green  color_red  size_L  size_M  size_XL  \
0   10.1       False         True      False   False    True    False   
1   13.5       False        False       True    True   False    False   
2   15.3        True        False      False   False   False     True   

   classlabel_class1  classlabel_class2  
0              False               True  
1               True              False  
2              False               True

In [41]:
pd.get_dummies(df_cat[['price', 'color']],drop_first=True)

price  color_green  color_red
0   10.1         True      False
1   13.5        False       True
2   15.3        False      False

In [11]:
#train test split
df_wine=pd.read_csv('/Users/libinvarghese/Documents/Jesna/Git_ML/ML_algorithms_Scratch/data/wine'
'.csv')

In [13]:
df_wine.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='object')

In [14]:
df_wine.Wine.unique()

array([1, 2, 3])

In [21]:
from sklearn.model_selection import train_test_split
X =df_wine.iloc[:,1:]
y = df_wine['Wine']
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=1)

In [22]:
y_train.unique()

array([2, 1, 3])

In [33]:
#min_maxscaling/normalization
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler_norm = MinMaxScaler()
x_train_scale_norm = scaler_norm.fit_transform(x_train)
x_test_scale_norm=scaler_norm.transform(x_test)

scaler_std = StandardScaler()
x_train_scale_std = scaler_std.fit_transform(x_train)
x_test_scale_std=scaler_std.transform(x_test)



In [29]:
x_train_scale[0,:]

array([0.27631579, 0.18979592, 0.40522876, 0.42196532, 0.11956522,
       0.2137931 , 0.24472574, 0.78      , 0.38801262, 0.09556314,
       0.45217391, 0.36630037, 0.16396104])

In [32]:
ex =np.array([0,1,2,3,4,5])
stan = ex-ex.mean()/ex.std()
norm = (ex-ex.min())/(ex.max()-ex.min())
print(stan)
print(norm)

[-1.46385011 -0.46385011  0.53614989  1.53614989  2.53614989  3.53614989]
[0.  0.2 0.4 0.6 0.8 1. ]


In [40]:
#feature importance
from sklearn.ensemble import RandomForestClassifier
X =df_wine.iloc[:,1:]
feat_labels =X.columns
y = df_wine.Wine
forest = RandomForestClassifier(n_estimators=500,random_state=10)
forest.fit(X,y)
importance = forest.feature_importances_
indices= np.argsort(importance)[::-1]
for f in range(len(indices)):
    print(feat_labels[indices[f]],'------',importance[indices[f]])





Color.int ------ 0.1699501253871795
Proline ------ 0.15349683511057924
Flavanoids ------ 0.14942607710898434
Alcohol ------ 0.12743517566397264
OD ------ 0.12489101429868281
Hue ------ 0.07851725674737103
Phenols ------ 0.049753355705069315
Mg ------ 0.03304413015877387
Acl ------ 0.030922629171937034
Malic.acid ------ 0.029732532970430426
Proanth ------ 0.02644061967892234
Ash ------ 0.014564604233599922
Nonflavanoid.phenols ------ 0.01182564376449752
