In [1]:
import pandas as pd
import numpy as np
df_wine=pd.read_csv('/Users/libinvarghese/Documents/Jesna/Git_ML/ML_algorithms_Scratch/data/wine'
'.csv')

In [2]:
#train_test_split
from sklearn.model_selection import train_test_split

X = df_wine.iloc[:,1:]
y = df_wine.iloc[:,1]
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)


In [3]:
print(f'x_train:{x_train.shape} x_x_test:{x_test.shape}')
print(f'y_train:{y_train.shape} y_test:{y_test.shape}')

x_train:(124, 13) x_x_test:(54, 13)
y_train:(124,) y_test:(54,)


In [4]:
#standrdize input data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

In [9]:
#covariance 
cov_data = np.cov(x_train_scaler.T)
eigen_vals, eigen_vecs = np.linalg.eig(cov_data)
eigen_vals.shape[0]

13

In [11]:
eigen_pairs = [(np.abs(eigen_vals[i]), eigen_vecs[:,i]) for i in range(eigen_vals.shape[0])]
eigen_pairs.sort(key=lambda k:k[0],reverse=True)

In [12]:
eigen_pairs

[(np.float64(5.048020196030455),
  array([ 0.1687399 , -0.25828114,  0.02289513, -0.25933973,  0.14665826,
          0.38720993,  0.41972155, -0.28155737,  0.30974284, -0.06159091,
          0.29064335,  0.35706719,  0.31376888])),
 (np.float64(2.5910615777932025),
  array([ 0.4629211 ,  0.22739021,  0.30710458, -0.01411108,  0.34077597,
          0.06521239, -0.04465878,  0.05299909,  0.05692405,  0.53375317,
         -0.27934865, -0.21252392,  0.32088363])),
 (np.float64(1.431503329703738),
  array([ 0.20625653,  0.06701835, -0.6519758 , -0.53626901, -0.32375806,
         -0.11661277, -0.05170325, -0.15492178,  0.00158411,  0.17968757,
         -0.21430883, -0.08296022,  0.1005847 ])),
 (np.float64(0.8983904377499822),
  array([ 0.04280992,  0.11763154,  0.04330674,  0.16518699, -0.53773204,
          0.22913204,  0.12519447,  0.47482375,  0.5704964 ,  0.1453865 ,
         -0.102132  ,  0.07892158, -0.09548031])),
 (np.float64(0.7220792687819645),
  array([-0.07125754, -0.64454937,  

In [16]:
W = np.empty((eigen_vecs.shape[1],4))
for i in range(4):
    W[:,i]=eigen_pairs[i][1]
print(W)

[[ 0.1687399   0.4629211   0.20625653  0.04280992]
 [-0.25828114  0.22739021  0.06701835  0.11763154]
 [ 0.02289513  0.30710458 -0.6519758   0.04330674]
 [-0.25933973 -0.01411108 -0.53626901  0.16518699]
 [ 0.14665826  0.34077597 -0.32375806 -0.53773204]
 [ 0.38720993  0.06521239 -0.11661277  0.22913204]
 [ 0.41972155 -0.04465878 -0.05170325  0.12519447]
 [-0.28155737  0.05299909 -0.15492178  0.47482375]
 [ 0.30974284  0.05692405  0.00158411  0.5704964 ]
 [-0.06159091  0.53375317  0.17968757  0.1453865 ]
 [ 0.29064335 -0.27934865 -0.21430883 -0.102132  ]
 [ 0.35706719 -0.21252392 -0.08296022  0.07892158]
 [ 0.31376888  0.32088363  0.1005847  -0.09548031]]


In [17]:
x_train_pca = x_train_scaler.dot(W)

In [18]:
x_train_pca.shape

(124, 4)