In [1]:

import numpy as np
from perceptron import Perceptron,Perceptron_Pytorch
import torch


In [2]:
X = np.array([
    [2, 3],
    [1, 1],
    [2, 1],
    [-1, -1],
    [-2, -3],
    [-1, -2]
])

y = np.array([1, 1, 1, -1, -1, -1])
model = Perceptron(learn_rate=0.01)
model.fit(X,y)

In [4]:
model.predict(np.array([[2,3],[2,1],[-1, -2]]))

AttributeError: 'numpy.ndarray' object has no attribute 'float'

In [2]:
X = torch.tensor([
    [2, 3],
    [1, 1],
    [2, 1],
    [-1, -1],
    [-2, -3],
    [-1, -2]
])

y = torch.tensor([1, 1, 1, -1, -1, -1])
model = Perceptron_Pytorch(learn_rate=0.01)
model.fit(X,y)

mps:0
mps:0


In [3]:
x_pre =torch.tensor([[2,3],[2,1],[-1, -2]])
model.predict(x_pre)

tensor([[ 1.],
        [ 1.],
        [-1.]], device='mps:0')

In [4]:
print( torch.backends.mps.is_available())

True


In [4]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

torch.dot(a, b)


tensor(32.)

In [5]:
A = torch.randn(3, 4)
B = torch.randn(4, 1)

torch.matmul(A, B)
# OR
A @ B


tensor([[ 1.0043],
        [-0.5094],
        [-1.2014]])

In [6]:
A

tensor([[-1.7089,  0.2987,  0.3073, -0.0602],
        [-0.3160, -0.8942, -0.8632,  1.5488],
        [-0.6534, -0.4605, -1.5788, -0.2131]])

In [7]:
import torch
data =torch.arange(0,50).float().reshape(10,-1)
data

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

In [15]:
lc = torch.nn.Linear(5,3)
lc.weight


Parameter containing:
tensor([[ 0.1238, -0.1657,  0.1849, -0.4383,  0.4221],
        [-0.2102,  0.0482, -0.0655, -0.3234,  0.1954],
        [ 0.0944,  0.2166,  0.2993, -0.1536,  0.0832]], requires_grad=True)

In [18]:
out =lc(data)

In [19]:
lc.weight

Parameter containing:
tensor([[ 0.1238, -0.1657,  0.1849, -0.4383,  0.4221],
        [-0.2102,  0.0482, -0.0655, -0.3234,  0.1954],
        [ 0.0944,  0.2166,  0.2993, -0.1536,  0.0832]], requires_grad=True)